# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='belstop',
            name='accepts_belPoints',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='belstop',
            name='spots_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='belstop',
            name='times_available',
            field=models.CommaSeparatedIntegerField(default=0, max_length=200),
        ),
    ]
